% Set default properties for axes and text
set(groot, 'DefaultAxesFontName', 'Times New Roman', ...
           'DefaultAxesFontSize', 14, ...
           'DefaultAxesFontWeight', 'normal', ...
           'DefaultTextFontName', 'Times New Roman', ...
           'DefaultTextFontSize', 24, ...
           'DefaultTextInterpreter', 'latex', ...
           'DefaultTextFontWeight', 'normal', ...
           'DefaultLegendInterpreter', 'latex', ...
           'DefaultLegendFontName', 'Times New Roman', ...
           'DefaultLegendFontSize', 16, ...
           'DefaultLegendFontWeight', 'normal', ...
           'DefaultColorbarFontName', 'Times New Roman', ...
           'DefaultColorbarFontSize', 20);